### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by CatCakeCandle** [allure-framework/allure-java#435] opened 2020-04-07 09:08 UTC
it's occasional:
run as scheduled task. 

jdk8 
allure-testng 2.12.1
testng 7.0.0

> 
```
java.util.ConcurrentModificationException: null
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1387) ~[?:1.8.0_242]
	at java.util.Hashtable.putAll(Hashtable.java:523) ~[?:1.8.0_242]
	at io.qameta.allure.util.PropertiesUtils.loadAllureProperties(PropertiesUtils.java:41) ~[allure-java-commons-2.12.1.jar!/:2.12.1]
	at io.qameta.allure.util.ResultsUtils.getProvidedLabels(ResultsUtils.java:238) ~[allure-java-commons-2.12.1.jar!/:2.12.1]
	at io.qameta.allure.testng.AllureTestNg.startTestCase(AllureTestNg.java:266) ~[allure-testng-2.12.1.jar!/:2.12.1]
	at io.qameta.allure.testng.AllureTestNg.startTestCase(AllureTestNg.java:247) ~[allure-testng-2.12.1.jar!/:2.12.1]
	at io.qameta.allure.testng.AllureTestNg.onTestStart(AllureTestNg.java:236) ~[allure-testng-2.12.1.jar!/:2.12.1]
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:210) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:557) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172) [testng-7.0.0.jar!/:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) [testng-7.0.0.jar!/:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) [testng-7.0.0.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by asolntsev** [comment] 2020-10-23 19:38
@CatCakeCandle Can you reproduce the issue with latest Java and Allure? 
Java 1.8.0_242 is quite outdated. `ConcurrentModificationException` might be fixed in newer versions.

**Comment by eroshenkoam** [comment] 2020-10-24 09:53
You could reopen issue if you provide example

**Closed by eroshenkoam** 2020-10-24 09:53 UTC

**Comment by boris-karpov** [comment] 2021-06-29 16:03
It is very difficult to reproduce the issue.
We catch the same exception occasionally, with almost the same stack trace (see below), when starting tests by testng dataProvider in parallel threads. In every such a thread `io.qameta.allure.util.PropertiesUtils.loadAllureProperties` is executed, which is copying `System.Properties` entirely.

	public static Properties loadAllureProperties() {
		final Properties properties = new Properties();
		loadPropertiesFrom(ClassLoader.getSystemClassLoader(), properties);
		loadPropertiesFrom(Thread.currentThread().getContextClassLoader(), properties);
		properties.putAll(System.getProperties());
		return properties;
	} 


`Properties` class is not thread safe in all Java versions. 

`ConcurrentModificationException` occurs when another thread changes `System.Properties` during the copying by
`properties.putAll(System.getProperties());`

It would be much appreciated if Allure team made the work with `System.Properties`  thread safe. Thank you.


jdk 1.8.0_292
allure-testng 2.14.0
testng 7.4.0

	java.util.ConcurrentModificationException
		at java.util.Hashtable$Enumerator.next(Hashtable.java:1387)
		at java.util.Hashtable.putAll(Hashtable.java:523)
		at io.qameta.allure.util.PropertiesUtils.loadAllureProperties(PropertiesUtils.java:41)
		at io.qameta.allure.util.ResultsUtils.getProvidedLabels(ResultsUtils.java:238)
		at io.qameta.allure.testng.AllureTestNg.startTestCase(AllureTestNg.java:285)
		at io.qameta.allure.testng.AllureTestNg.startTestCase(AllureTestNg.java:266)
		at io.qameta.allure.testng.AllureTestNg.onTestStart(AllureTestNg.java:255)
		at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:103)
		at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
		at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:569)
		at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
		at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
		at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

**Comment by asolntsev** [comment] 2021-06-30 05:58
@boris-karpov But how is it technically possible? I don't see any reasonable solution except making `System.Properties` thread-safe in Java.

Probably it's better to avoid concurrent modification of `System.Properties` by multiple threads? It seems to be a bad idea anyway.
