### ISSUE TITLE
🐞: JUnit 5 @Nested class is not considered a sub-suite of parent class

### ISSUE THREAD

**Issue by pedrolamarao** [allure-framework/allure-java#992] opened 2024-01-19 14:34 UTC
### What happened?

`@Nested` is JUnit feature that allows a test hierarchy with more levels than the basic two, class and method.
Allure has the similar concept of a super/sub test suite relation.
Currently, Allure Junit 5 integration does interprets `@Nested` as a top-level suite instead of a sub-suite of the parent class.
I suggest that JUnit 5 `@Nested` classes be interpreted as sub-suites of the parent class.

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.25.0

### What version of Allure Report you are using?

2.25.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment] 2024-02-01 18:35
Duplicate of #391

**Closed by baev** 2024-02-01 18:35 UTC
Labels: type:bug, triage
