### ISSUE TITLE
[TestNG] Allure report does not display enabled=false tests

### ISSUE THREAD

**Issue by choojoykin** [allure-framework/allure-java#209] opened 2018-03-02 06:24 UTC
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure report does not display enabled=false tests. Allure results directory does not contain the enabled test result.json file

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
mark test as enabled=false

#### What is the expected behavior?
Report show enabled=false test as skipped

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | testng@6.9.10 |
| Allure integration | allure-testng@2.0-BETA22 |
| Generate report using | allure-maven@2.9|

**Comment by baev** [comment] 2018-10-31 16:53
Duplicate of #49

**Closed by baev** 2018-10-31 16:53 UTC
Labels: theme:testng, type:bug, work:backlog
