### ISSUE TITLE
[allure-testng] Could not write Allure test result

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-java#197] opened 2018-02-11 13:27 UTC
from https://github.com/allure-framework/allure2/issues/738

[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
In my testcase,if run failed,it will throw AllureResultsWriteException

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.12 |
| Allure adaptor | allure-testng@2.0-BETA21 |
| Generate report using | allure-maven@2.19 |

#### Other information
 `
 io.qameta.allure.AllureResultsWriteException: Could not write Allure test result
 `
 `
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:43)
 `
 `
	at io.qameta.allure.AllureLifecycle.lambda$writeTestCase$12(AllureLifecycle.java:197)
 `
 `
	at java.util.Optional.ifPresent(Optional.java:159)
 `
 `
	at io.qameta.allure.AllureLifecycle.writeTestCase(AllureLifecycle.java:195)
 `
 `
	at io.qameta.allure.testng.AllureTestNg.onTestFailure(AllureTestNg.java:260)
 `
 `
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1738)
  `
 `
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1722)
  `
 `
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1258)
  `
 `
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
 `
 `
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
 `
 `
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 `
 `
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 `
 `
	at java.lang.Thread.run(Thread.java:748)
 `
 `
Caused by: java.nio.channels.ClosedByInterruptException
  `
 `
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
 `
 `
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
  `
 `
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
 `
 `
	at java.nio.channels.Channels.writeFully(Channels.java:101)
 `
 `
	at java.nio.channels.Channels.access$000(Channels.java:61)
  `
 `
	at java.nio.channels.Channels$1.write(Channels.java:174)
 `
 `
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2085)
  `
 `
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1127)
 `
 `
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3898)
  `
 `
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3164)
  `
 `
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:41)
 `
 `
	... 12 more
`

**Comment by baev** [comment] 2018-02-11 13:28
@EzioAuditoreDeFirenze  it would be much easier for us if you provide a sample project to reproduce the problem

**Comment by Ubermensch01** [comment] 2018-03-03 01:30
@baev I had a very similar issue recently with allure-testng:2.6.0, it started with the following:
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;

Updating the jackson-databind, jackson-annotation and jackson-core dependencies resolved the issue for me. Consider updating those dependencies in allure-java-commons component.

**Comment by tlytvyn** [comment] 2018-03-14 12:43
Updating jackson-core, jackson-annotation and jackson-databind to version 2.9.4 fixed the issue

**Comment by MickyOwly** [comment] 2018-05-09 12:32
I added to my project: 
`        <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.9.5</version>
    </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.5</version>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.5</version>
        </dependency>`

However issue is still on going when running tests in parallel after retry:

> `Exception in thread "TestNG-test=Test-6" io.qameta.allure.AllureResultsWriteException: Could not write Allure test result
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:43)
	at io.qameta.allure.AllureLifecycle.lambda$writeTestCase$12(AllureLifecycle.java:197)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.qameta.allure.AllureLifecycle.writeTestCase(AllureLifecycle.java:195)
	at io.qameta.allure.testng.AllureTestNg.onTestFailure(AllureTestNg.java:272)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1042)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2085)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment2(UTF8JsonGenerator.java:1400)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1347)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1228)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:453)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3164)
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:41)
`

**Comment by MickyOwly** [comment] 2018-05-17 08:06
@Ubermensch01 @baev @tlytvyn any idea how I can do further debugging?
Would appreciate any help.

**Comment by AutomatedOwl** [comment] 2018-07-11 13:47
@baev can you please review https://github.com/allure-framework/allure2-model/pull/16 ?

**Comment by baev** [comment] 2018-07-11 14:08
@AutomatedOwl done, check it out

**Comment by AutomatedOwl** [comment] 2018-07-19 08:48
Looks like it's fixed in 2.7.0 :) 
Thanks @baev for your review

**Closed** 2018-07-19 10:51 UTC
Labels: theme:api, theme:testng, type:bug, work:selected for dev

**Comment by AvrahamAtia** [comment] 2018-12-03 15:00
Still a bug at 2.8.0, Log:
Exception in thread "TestNG-test=AccountTab - Sanity-1" io.qameta.allure.AllureResultsWriteException: Could not write Allure test result

**Comment by baev** [comment] 2018-12-03 16:01
@AvrahamAtia thats maybe a different issue. Could you please provide an example project to reproduce the problem as well as providing full stack trace of the error?

**Comment by AvrahamAtia** [comment] 2018-12-04 12:44
@baev It happen When I am using timeOut property of TestNG, Do you any idea why it happen only when I am using timeOut?!

**Comment by AvrahamAtia** [comment] 2018-12-04 12:45
Full stack trace:
*
at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:43)
10:59:48 	at io.qameta.allure.AllureLifecycle.writeTestCase(AllureLifecycle.java:400)
10:59:48 	at io.qameta.allure.testng.AllureTestNg.onTestFailure(AllureTestNg.java:272)
10:59:48 	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
10:59:48 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
10:59:48 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1042)
10:59:48 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
10:59:48 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
10:59:48 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:59:48 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:59:48 	at java.lang.Thread.run(Thread.java:748)
10:59:48 Caused by: java.nio.channels.ClosedByInterruptException
10:59:48 	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
10:59:48 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
10:59:48 	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
10:59:48 	at java.nio.channels.Channels.writeFully(Channels.java:101)
10:59:48 	at java.nio.channels.Channels.access$000(Channels.java:61)
10:59:48 	at java.nio.channels.Channels$1.write(Channels.java:174)
10:59:48 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
10:59:48 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
10:59:48 	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
10:59:48 	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1138)
10:59:48 	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3910)
10:59:48 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3176)
10:59:48 	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:41)
10:59:48 	... 10 more
10:59:48 	Suppressed: java.nio.channels.ClosedChannelException
10:59:48 		at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
10:59:48 		at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:199)
10:59:48 		at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
10:59:48 		at java.nio.channels.Channels.writeFully(Channels.java:101)
10:59:48 		at java.nio.channels.Channels.access$000(Channels.java:61)
10:59:48 		at java.nio.channels.Channels$1.write(Channels.java:174)
10:59:48 		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
10:59:48 		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
10:59:48 		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
10:59:48 		at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:42)
10:59:48 		... 10 more*

**Comment by AvrahamAtia** [comment] 2018-12-05 12:46
@baev

**Comment by AutomatedOwl** [comment] 2018-12-05 14:31
@baev @AvrahamAtia  it's reproduced using Maven with JDK8. Upgrading to JDK11 seems to fix the issue.

**Comment by AvrahamAtia** [comment] 2018-12-06 09:11
@AutomatedOwl Should I downgrade TestNG or allure? I prefer leave JDK8 not update to JDK11..
