### ISSUE TITLE
🐞: Allure.getLifecycle().updateTestCase() no effect since allure-bom v2.26.0

### ISSUE THREAD

**Issue by alexKazarin** [allure-framework/allure-java#1123] opened 2024-09-01 14:28 UTC
### What happened?
Method updateTestCase() stopped to work in @After block of test framework, ex.:

>     Allure.getLifecycle().updateTestCase(uuid, testResult -> 
>        testResult.setStatus(Status.SKIPPED).setDescription("testDescription"));

Implementation:
>     @After("@knownissue")
>     public void knownIssueInScenario(Scenario scenario) {
>         if (scenario.isFailed()) {
>             AllureLifecycleCustom.updCurrentTestDescriptionAndStatus(
>                     "Test has known issue", SKIPPED);
>         }
>     }
>     ...  
>     public static void updCurrentTestDescriptionAndStatus(String testDescription, Status testStatus) {
>         Optional<String> testCaseUuid = getCurrentTestUuid();
>         testCaseUuid.ifPresent(uuid -> Allure.getLifecycle()
>                 .updateTestCase(uuid, testResult -> testResult.setStatus(testStatus).setDescription(testDescription)));
>     }

### Expected Behaviour
Test marked as skipped in Report.
<img width="845" alt="image" src="https://github.com/user-attachments/assets/ec6074c8-c33c-4f91-8e29-6999f16694a8">

### Actual Behaviour
Test marked as failed in Report.
<img width="836" alt="image" src="https://github.com/user-attachments/assets/60884961-b14e-4c87-bc5e-a3c793037a8f">

### Details
Problem appeared in allure-bom since version [2.26.0](https://mvnrepository.com/artifact/io.qameta.allure/allure-bom/2.26.0). 
In version [2.25.0](https://mvnrepository.com/artifact/io.qameta.allure/allure-bom/2.25.0) no this bug, all works as expected.
Tried latest version 2.29.0 of the lib, problem still exists. 
Possibly [this bug fix](https://github.com/allure-framework/allure-java/issues/373) could influence.

### Tech. details
- Java 17
- Maven 3.9.8
- Cucumber [7.18.0](https://mvnrepository.com/artifact/io.cucumber/cucumber-bom/7.18.0)

### What Allure Integration are you using?
allure-cucumber7-jvm

### What version of Allure Integration you are using?
2.26.0

### What version of Allure Report you are using?
2.26.0

### Code of Conduct
- [X] I agree to follow this project's Code of Conduct

**Comment by IlyaHarlamov** [comment] 2024-09-24 11:27
Hey @alexKazarin, I have also created one similar issue time ago, maybe it may help: https://github.com/allure-framework/allure-java/issues/1119
Instead of updating it via hooks, you may try to do the same by implementing `TestLifecycleListener` (see my comment in issue #1119)

**Comment by baev** [comment] 2024-09-24 17:09
Duplicate of #1119

**Closed by baev** 2024-09-24 17:09 UTC
Labels: type:bug, triage
