### ISSUE TITLE
Test body is missed in report if run test via "java org.testng.TestNG suite.xml"

### ISSUE THREAD

**Issue by shynkevichalex** [allure-framework/allure-java#301] opened 2018-12-04 20:18 UTC
Pom.xml configured via documentation https://docs.qameta.io/allure/#_maven_3.
When I run test via "mvn test" all works fine.

But I would build jar of test project then extract it on slaves and run tests via command "java org.testng.TestNG suite.xml"

#### Current result
Test report generates but test body is missed.
![image](https://user-images.githubusercontent.com/44173756/49470112-35c8f280-f81a-11e8-9647-8cb190c9d300.png)

#### Is there any solution to display test body when test run in this way?

**Comment by LisaHoney** [comment] 2019-06-10 04:45
I have the same question，Have you found the solution？

**Comment by ucdevinda123** [comment] 2019-08-20 07:10
Currently I am facing the same issue. I have asked the same question on stack-overflow. [https://stackoverflow.com/questions/57566093/allure-test-ng-report-testbody-is-missing ](url)
@baev  do you know any fix for this desperately looking for it. :-)

**Comment by ucdevinda123** [comment] 2019-08-20 07:16
@LisaHoney  @shynkevichalex did you find any solutions for this :-)

**Comment by KroganUrdnot** [comment] 2019-08-26 07:42
Guys, please update if any solution or workaround found

**Comment by ucdevinda123** [comment] 2019-08-27 02:16
@KroArtem Yeah  same here desperately  waiting for a workaround or solution.

**Comment by ucdevinda123** [comment] 2019-09-08 01:16
@baev  Any update on this issue?

**Comment by adamchenwei** [comment] 2019-09-16 14:14
Observe same issue when in jest-allure. any fixes???

**Comment by ucdevinda123** [comment] 2019-09-18 16:00
@baev can you reply please?

**Comment by baev** [comment] 2019-09-18 16:03
You need to add AspectJWeaver javaagent to your command:

`java -javaagent:aspectjweaver.jar -jar tests.jar org.testng.TestNG suite.xml`

**Comment by ss-04** [comment] 2019-09-18 17:35
AspectJWeaver agent is added as below 

<argLine>				javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar "
</argLine>

Should we mention suite.xml as well?

**Comment by ss-04** [comment] 2019-10-17 05:02
@baev - Any updates on the issue?

**Comment by ss-04** [comment] 2019-10-17 05:02
@baev - Any updates on the issue?

**Comment by pokeahontas** [comment] 2019-10-30 11:42
@baev I have the same issue and reportd here https://github.com/allure-framework/allure-java/issues/398 . Please help us fix this

**Comment by gsai0205** [comment] 2020-03-10 21:55
@baev Any update on this issue?
Do we have any workaround?

**Comment by shalevoren** [comment] 2020-04-13 08:22
@baev Any update on this issue? i have same problem

**Comment by mohitrathi92** [comment] 2020-07-05 05:24
any updates?

**Comment by biletsky** [comment] 2020-12-01 13:57
any updates?

**Comment by galkina-anna** [comment] 2020-12-17 11:01
Was having the same issue, after hours and days of debugging found the solution that works for me. 

Added **aop.xm**l into **resources/META-INF folder** (if these is no such folder - create one) 

The content of such xml should be:
```
<aspectj>
    <weaver> <!--<weaver options="-verbose -showWeaveInfo">-->
        <include within="io.qameta.allure..*"/>
        <include within="org.testng..*"/>
        <include within="com.company.testautomation..*"/>
    </weaver>
</aspectj>

```


After that Test body with steps and screenshots are visible again.

**Comment by biletsky** [comment] 2020-12-18 12:50
@galkina-anna         <include within="com.changethispath.testautomation..*"/> Which path is it?

**Comment by galkina-anna** [comment] 2021-01-18 17:52
> @galkina-anna `<include within="com.changethispath.testautomation..*"/>` Which path is it?

path to tests package

**Comment by VladShapeshifter** [comment] 2021-04-23 12:26
Try to use earlier version of aspectjweaver, e.g. 1.9.0

**Comment by Sergiy1987** [comment] 2021-05-19 21:19
@galkina-anna this aol.xml file should be added for test resources or for the main part of a project?

And a path for tests should be like src/test/resources/features?

Now I can't resolve this problem with your fix. Can you explain how you fix this problem?
Thank you.

![Allure Report](https://user-images.githubusercontent.com/16984941/118885763-d8995c80-b900-11eb-8708-b52434fb05fa.png)

**Comment by mohammedghouse36** [comment] 2021-05-31 12:25
Could someone please given valid solution. I too facing this issue.

**Comment by anna-shchurok** [comment] 2022-02-04 19:29
@Sergiy1987 sorry for slight delay in reply.


>  file should be added for test resources or for the main part of a project?

it should be in both places. Same file, same folder

>And a path for tests should be like src/test/resources/features? 

for me it was path to parent folder which contains page objects or test classes. As far as I understand just the path where allure need to search mentioning of itself

>Can you explain how do you solve this problem for your project?

Basically the root cause of it this issue was third-party jar that also was using allure, so some collisions appeared. When I added those 2 files with direct mentioning where allure should search - it worked out for me.

**Comment by jacksonwen001** [comment] 2022-02-09 05:39
Is anybody have another workaround? I met the same issue.

**Comment by jacksonwen001** [comment] 2022-02-09 07:34
It would be fine if you use the gradle to generate allure report.

**Comment by Tal-Raanan** [comment] 2022-03-16 09:58
Hi all,
I'm using IntelliJ (TestNG + Maven). **### I found an easy solution for this issue**: apparently running xml suites directly via the IntelliJ would not work fine, as described in this topic. 
My solution is:
1. Download a compatible Maven version from [https://maven.apache.org/download.cgi]
2. Extract the files (remember the path)
3. Edit System Environment Variables: 
**Add 2 System variables**: 'M2_HOME' and 'MAVEN_HOME' - provide the relevant Maven installation library path - NOT including the bin file (e.g. C:\Automation\Maven\apache-maven-3.8.5-bin\apache-maven-3.8.5)  
**Add 2 Paths**: %M2_HOME%\bin and %MAVEN_HOME%\bin
4. **Restart windows**
5. Open cmd and verify the implementation by inserting 'mvn' and observing data (errors are fine at this moment, system should recognize the command 'mvn')
6. Open IntelliJ's terminal and insert the next command: 'mvn test -Pweb' (P=profile - as configured in pom.xml, web=profile name - change it due to your configuration).
7. After execution browse to allure report and observe results - Test body (and a screenshot, if implemented) should be appeared   

Attached is an example for pom.xml profile:
    <profiles>
        <profile>
            <id>web</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                                 <version>2.22.1</version>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>TestNGWeb.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>

**Comment by Fulcrum81** [comment] 2022-03-24 22:25
I've been having this issue with allure-testng v.2.17.0 and TestNG v.7.5.0

The only thing that helped me was downgrading TestNG to 7.4.0 after which the test bodies started showing as they should.

So try playing around with atture-testng and testng versions to find the compatible combination

**Comment by david-m-globant** [comment] 2022-04-07 21:15
i solved this issue using code of this [question](https://stackoverflow.com/questions/60249288/unable-to-generate-allure-report-using-testng-and-maven) 

`	<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.11.2</version>
				<configuration>
					<reportDirectory>${basedir}\target\allure-report</reportDirectory>
				</configuration>
			</plugin>
		</plugins>
	</reporting>`

**Closed** 2022-10-25 03:47 UTC
Labels: type:bug, work:backlog, theme:testng
