### ISSUE TITLE
okhttp3 adaptor ignore before/after for class/test method for junit5 test framework

### ISSUE THREAD

**Issue by rosolko** [allure-framework/allure-java#203] opened 2018-02-18 09:53 UTC
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

okhttp3 adaptor ignore *before/after* method for *class/test* for junit5 test framework.
Attach as simple attachment w/o any order.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Execute okhttp request in *before/after* method for *class/test*.

#### What is the expected behavior?

Attach reqest/response with right order inside test.

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | junit@5.0.1 |
| Allure integration | allure-junit5@2.0-BETA22 |
| Generate report using | allure-gradle@2.5.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment] 2018-10-31 16:16
Actually the problem is that attachments can not be created without test/fixture context

**Comment by baev** [comment] 2018-10-31 16:16
Duplicate of #227

**Closed by baev** 2018-10-31 16:16 UTC
