### ISSUE TITLE
🐞: @Steps not working when with Quarkus/JUnit5

### ISSUE THREAD

**Issue by NirGrotel** [allure-framework/allure-java#932] opened 2023-07-03 10:53 UTC
### What happened?

My infra is working with JUnit5 and Quarkus.
i have created some api tests and i added @Step to methods used in the test.
unfortunately I don't get the steps in the report.

do you guys know what I can do about it?

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.14.0

### What version of Allure Report you are using?

2.10.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment] 2023-07-04 10:46
Duplicate of https://github.com/allure-framework/allure2/issues/1428

**Closed by baev** 2023-07-04 10:46 UTC
Labels: type:bug

**Comment by baev** [comment] 2024-01-31 23:13
https://github.com/allure-framework/allure2/issues/1428#issuecomment-1920149626
