### ISSUE TITLE
[JUnit4] Steps not working with JUnit timeouts

### ISSUE THREAD

**Issue by martynovig** [allure-framework/allure-java#158] opened 2017-11-07 21:03 UTC
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Steps in allure report is not displayed

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

`@Test(timeout = 100000)
public void testMethod() {
  // Any steps
}
`

#### What is the expected behavior?
Steps is displayed in allure report

#### What is the motivation / use case for changing the behavior?
Use timeouts in tests

#### Please tell us about your environment:

| Environment | Version |
| --- | --- |
| Allure version | 2.4.1 |
| Test framework | JUnit@4.12 |
| Allure integration | allure-junit4@2.0-BETA19 |
| Generate report using | allure-maven@2.8 |
| Runner | BlockJUnit4ClassRunner |

#### Other information 
1) It may be caused because junit create new thread in FailOnTimeout.
2) It may be caused with StepsAspects because attachments works correctly.

**Comment by aiannucci** [comment] 2017-11-09 19:41
This is a duplicate of #108

**Closed** 2018-02-06 16:26 UTC
